// slabs-forge

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/slabs-forge/klabs-api/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Modules returns a ModuleInformer.
	Modules() ModuleInformer
	// ModuleLinks returns a ModuleLinkInformer.
	ModuleLinks() ModuleLinkInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Modules returns a ModuleInformer.
func (v *version) Modules() ModuleInformer {
	return &moduleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ModuleLinks returns a ModuleLinkInformer.
func (v *version) ModuleLinks() ModuleLinkInformer {
	return &moduleLinkInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
