// slabs-forge

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	slabsforgev1 "github.com/slabs-forge/klabs-api/apis/slabs.forge/v1"
	versioned "github.com/slabs-forge/klabs-api/clientset/versioned"
	internalinterfaces "github.com/slabs-forge/klabs-api/informers/externalversions/internalinterfaces"
	v1 "github.com/slabs-forge/klabs-api/listers/slabs.forge/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ModuleLinkInformer provides access to a shared informer and lister for
// ModuleLinks.
type ModuleLinkInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ModuleLinkLister
}

type moduleLinkInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewModuleLinkInformer constructs a new informer for ModuleLink type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewModuleLinkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredModuleLinkInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredModuleLinkInformer constructs a new informer for ModuleLink type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredModuleLinkInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SlabsV1().ModuleLinks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SlabsV1().ModuleLinks(namespace).Watch(context.TODO(), options)
			},
		},
		&slabsforgev1.ModuleLink{},
		resyncPeriod,
		indexers,
	)
}

func (f *moduleLinkInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredModuleLinkInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *moduleLinkInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&slabsforgev1.ModuleLink{}, f.defaultInformer)
}

func (f *moduleLinkInformer) Lister() v1.ModuleLinkLister {
	return v1.NewModuleLinkLister(f.Informer().GetIndexer())
}
