// slabs-forge

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/slabs-forge/klabs-api/clientset/versioned/typed/slabs.forge/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSlabsV1 struct {
	*testing.Fake
}

func (c *FakeSlabsV1) Modules(namespace string) v1.ModuleInterface {
	return &FakeModules{c, namespace}
}

func (c *FakeSlabsV1) ModuleLinks(namespace string) v1.ModuleLinkInterface {
	return &FakeModuleLinks{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSlabsV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
