// slabs-forge

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"net/http"

	v1 "github.com/slabs-forge/klabs-api/apis/slabs.forge/v1"
	"github.com/slabs-forge/klabs-api/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type SlabsV1Interface interface {
	RESTClient() rest.Interface
	ModulesGetter
	ModuleLinksGetter
}

// SlabsV1Client is used to interact with features provided by the slabs.forge group.
type SlabsV1Client struct {
	restClient rest.Interface
}

func (c *SlabsV1Client) Modules(namespace string) ModuleInterface {
	return newModules(c, namespace)
}

func (c *SlabsV1Client) ModuleLinks(namespace string) ModuleLinkInterface {
	return newModuleLinks(c, namespace)
}

// NewForConfig creates a new SlabsV1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*SlabsV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new SlabsV1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*SlabsV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &SlabsV1Client{client}, nil
}

// NewForConfigOrDie creates a new SlabsV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *SlabsV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new SlabsV1Client for the given RESTClient.
func New(c rest.Interface) *SlabsV1Client {
	return &SlabsV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *SlabsV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
