apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modules.slabs.forge
spec:
  group: slabs.forge
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                links:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    properties:
                      id: 
                        type: string
                        format: hostname
                      type:
                         type: string
                      name:
                         type: string
                    required: [id,type]
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - id
                context:
                  type: string
              required: [links,context]
          required: [spec]
  scope: Cluster
  names:
    plural: modules
    singular: module
    kind: Module
    shortNames:
      - mod