apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modulelinks.slabs.forge
spec:
  group: slabs.forge
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id: 
                  type: string
                  format: hostname
                type:
                  type: string
                name:
                  type: string
                context:
                  type: string
              required: [id,type,context]
          required: [spec]
  scope: Cluster
  names:
    plural: modulelinks
    singular: modulelink
    kind: ModuleLink
    shortNames:
      - link
      - lnk