// slabs-forge

// Code generated by lister-gen. DO NOT EDIT.

package v1

// ModuleListerExpansion allows custom methods to be added to
// ModuleLister.
type ModuleListerExpansion interface{}

// ModuleNamespaceListerExpansion allows custom methods to be added to
// ModuleNamespaceLister.
type ModuleNamespaceListerExpansion interface{}

// ModuleLinkListerExpansion allows custom methods to be added to
// ModuleLinkLister.
type ModuleLinkListerExpansion interface{}

// ModuleLinkNamespaceListerExpansion allows custom methods to be added to
// ModuleLinkNamespaceLister.
type ModuleLinkNamespaceListerExpansion interface{}
